------------------------------------------------SQL DAY - 1-----------------------------------------------------

-- CREATING A DATABASE

CREATE DATABASE EMPLOYEE;

-- CEATING A SCHEMA

CREATE SCHEMA EMPLOYEE;

-- CRAETING A TABLE EMPLOYEE

CREATE TABLE EMPLOYEE.EMPLOYEE_TEMP(

	EMP_ID INT,
	
	EMP_NAME VARCHAR(50)


);

-- INSERTING THE VALUES IN THE EMPLOYEE TABLE

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('1','RAHUL DHANOLA');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('2','GARVIT PANT');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('3','HARSH PANDEY');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('4','ASHIS');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('5','ARIHANT');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('6','BALARK SINGHAL');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('7','MAYANK');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('8','HIMANSHU');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('9','ABHISHEK');

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('10','DIPANSHU');

-- SHOWING ALL RECORDS OF A TABLE


-- ALTER TABKLE TO DEFINE A PRIMARY KEY

ALTER TABLE EMPLOYEE.EMPLOYEE_TEMP
ADD CONSTRAINT PRIMARY KEY(EMP_ID);


-- ALTER TABLE EMPLOYEE.EMPLOYEE_TEMP
-- DROP CONSTRAINT EMP_ID;

-- EMP_ID WITH VALUES GREATER THAN 2

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
WHERE EMP_ID>7;

-- EMP_ID WITH VALUES BETWEEN 5 TO 8

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
WHERE EMP_ID>5 AND EMP_ID<8;

-- EMP_ID WITH GIVEN VALUES ONLY

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
WHERE EMP_ID IN (2,5,7,6);

-- SHOW VALUES THAT STARTS WITH 'A'

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
WHERE EMP_NAME LIKE 'A%';

-- SHOW EMPLOYEE NAME WITH ONLY THREE CHARACTERS

SELECT *,LENGTH(EMP_NAME) FROM EMPLOYEE.EMPLOYEE_TEMP
WHERE LENGTH(EMP_NAME)=5;

-- WHERE CAN BE USED IN TO GIVE A CONDITION OR IN UPDATE STATEMENT

-- FIND NAMES START WITH A SUBSTRING WITHOUT LIKE

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
WHERE SUBSTRING(EMP_NAME,1,3)='RAH';

-- LIMIT KEYWORD SHOWS THE VALUES TO GIVEN NYMBER

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
LIMIT 5;

-- OFFSET KEYWORD IS USED TO SHIFT THE START POSITION OF LIMIT

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
LIMIT 2 OFFSET 4;

-- SELECT STATEMEMNNT SYNTAX

-- SELECT COLUMN_NAME FROM TABLE_NAME
-- WHERE CRITERIA
-- GROUP BY
-- HAVING ORDER BY LIMIT OFFSET;

-- HOW TO SELECT THE COLUMN IF ITS NAME IS BIG

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
ORDER BY EMP_ID DESC;

-- IS SAME AS 


SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP
ORDER BY 1 DESC;

-- SHOW EMPLOYEE NAME WITH THERE EMPLOYEE ID COUNT 

SELECT EMP_NAME, COUNT(EMP_ID) FROM EMPLOYEE.EMPLOYEE_TEMP
GROUP BY EMP_NAME;

-- -- UPDATE A TABLE

-- -- ALTER: IT IS A DATA DEFINITION COMMAND I.E. ONLY ON TABLE STRUCTURE
-- -- UPDATE: IT IS A DATA MANIPULATION COMMAND I.E. ONLY ON TABLE STRUCTURE

-- SELECT * FROM EMPLOYEE.TEMP; --

-- IN UPDATE WE HAVE TO GIVE THE WHERE CLAUSE ELSE IT WILL UPDATE ALL THE VALUES IN THE TABLE

INSERT INTO EMPLOYEE.EMPLOYEE_TEMP VALUES('11','CODECODE');

UPDATE EMPLOYEE.EMPLOYEE_TEMP
SET EMP_NAME ='VISHNU'
WHERE EMP_ID=11;

SELECT * FROM EMPLOYEE.EMPLOYEE_TEMP;

UPDATE 	EMPLOYEE.EMPLOYEE_TEMP
SET EMP_NAME='HELLO'
WHERE EMP_ID=200;

-- DELETING ALL VALUES FROM THE TABLE

DELETE FROM EMPLOYEE.EMPLOYEE_TEMP;

-- TO DELETE THE ENTIRE TABLE FROM THE DATABASE


DROP TABLE EMPLOYEE.EMPLOYEE_TEMP;

-- TWO VALUES UPDATE IN SQL

UPDATE EMPLOYEE.EMPLOYEE_TEMP
SET EMP_ID=12, EMP_NAME='NAME'
WHERE EMP_ID=11;

-- DIFFRENCE BETWEEN TRUNCATE AND DELETE * FROM TABLE

-- IF WE DO DELETE THAN IT WILL LEAVE SPACES IN THE DISK THAT IS CAUSE FRAGMENTATION BUT IF WE USE THE TRUNCATE THAN IT WILL DELETE THE TABLE AND ALSO DEFRAGMENT THE TABLE SPACE

-- YOU CAN USE GROUP BY ONLY AFTER WHERE CLAUSE IF USING

------------------------------------------------SQL DAY - 1-----------------------------------------------------